import type { GeneratedResponse } from "../api/types";

/** One entry in the constraint dock: either typed by the user or generated by the app. */
export interface AppliedConstraint {
  origin: "user" | "app";
  text: string;
}

/**
 * Split the editor's text into Alloy predicates, one per line. Blank lines and
 * `//` comments are dropped so the box can be annotated freely.
 */
export function parseConstraintDraft(draft: string): string[] {
  return draft
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("//"));
}

/**
 * Everything the session server adds on top of the translated model, in the order
 * it assembles them: paragraphs spliced into the model body, the generated
 * `__initial` predicate, then the per-solve wrapper.
 */
export function generatedParagraphs(generated: GeneratedResponse | null): AppliedConstraint[] {
  if (!generated?.available) return [];

  const paragraphs = [
    ...(generated.insertedFragments ?? []),
    ...(generated.initPredicate ? [generated.initPredicate] : []),
    ...(generated.wrapperFragments ?? [])
  ];

  return paragraphs
    .map((text) => text.trim())
    .filter((text) => text.length > 0)
    .map((text): AppliedConstraint => ({ origin: "app", text }));
}
